<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Uganda District / City Administrative Areas
    |--------------------------------------------------------------------------
    |
    | Source: UGA_District_Boundaries_2024 ArcGIS FeatureServer, NAME field.
    | The layer is described as updated against Uganda's 2024 census district
    | listing, official gazettes, and supporting geospatial reference data.
    |
    */
    'uganda_districts' => [
        'Abim',
        'Adjumani',
        'Agago',
        'Alebtong',
        'Amolatar',
        'Amudat',
        'Amuria',
        'Amuru',
        'Apaa',
        'Apac',
        'Arua',
        'Arua City',
        'Budaka',
        'Bududa',
        'Bugiri',
        'Bugweri',
        'Buhweju',
        'Buikwe',
        'Bukedea',
        'Bukomansimbi',
        'Bukwo',
        'Bulambuli',
        'Buliisa',
        'Bundibugyo',
        'Bunyangabu',
        'Bushenyi',
        'Busia',
        'Butaleja',
        'Butambala',
        'Butebo',
        'Buvuma',
        'Buyende',
        'Dokolo',
        'Fort Portal City',
        'Gomba',
        'Gulu',
        'Gulu City',
        'Hoima',
        'Hoima City',
        'Ibanda',
        'Iganga',
        'Isingiro',
        'Jinja',
        'Jinja City',
        'Kaabong',
        'Kabale',
        'Kabarole',
        'Kaberamaido',
        'Kagadi',
        'Kakumiro',
        'Kalaki',
        'Kalangala',
        'Kaliro',
        'Kalungu',
        'Kampala Capital City',
        'Kamuli',
        'Kamwenge',
        'Kanungu',
        'Kapchorwa',
        'Kapelebyong',
        'Karenga',
        'Kasese',
        'Kassanda',
        'Katakwi',
        'Kayunga',
        'Kazo',
        'Kibaale',
        'Kiboga',
        'Kibuku',
        'Kikuube',
        'Kiruhura',
        'Kiryandongo',
        'Kisoro',
        'Kitagwenda',
        'Kitgum',
        'Koboko',
        'Kole',
        'Kotido',
        'Kumi',
        'Kwania',
        'Kween',
        'Kyankwanzi',
        'Kyegegwa',
        'Kyenjojo',
        'Kyotera',
        'Lamwo',
        'Lira',
        'Lira City',
        'Luuka',
        'Luweero',
        'Lwengo',
        'Lyantonde',
        'Madi Okollo',
        'Manafwa',
        'Maracha',
        'Masaka',
        'Masaka City',
        'Masindi',
        'Mayuge',
        'Mbale',
        'Mbale City',
        'Mbarara',
        'Mbarara City',
        'Mitooma',
        'Mityana',
        'Moroto',
        'Moyo',
        'Mpigi',
        'Mubende',
        'Mukono',
        'Nabilatuk',
        'Nakapiripirit',
        'Nakaseke',
        'Nakasongola',
        'Namayingo',
        'Namisindwa',
        'Namutumba',
        'Napak',
        'Nebbi',
        'Ngora',
        'Ntoroko',
        'Ntungamo',
        'Nwoya',
        'Obongi',
        'Omoro',
        'Otuke',
        'Oyam',
        'Pader',
        'Pakwach',
        'Pallisa',
        'Rakai',
        'Rubanda',
        'Rubirizi',
        'Rukiga',
        'Rukungiri',
        'Rwampara',
        'Serere',
        'Sheema',
        'Sironko',
        'Soroti',
        'Soroti City',
        'Ssembabule',
        'Terego',
        'Tororo',
        'Wakiso',
        'Yumbe',
        'Zombo',
    ],
];
